version: '2.2'
services:

  es:
    container_name: es
    hostname: es
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m -Des.allow_insecure_settings=true"
      - xpack.security.enabled=false
      - bootstrap.system_call_filter=false
      - bootstrap.memory_lock=true
      - http.host=0.0.0.0
      - transport.host=localhost
      - cluster.name=itest
    mem_limit: 2g
    networks:
      - stack
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]

  kibana:
    container_name: kibana
    hostname: kibana
    image: docker.elastic.co/kibana/kibana:${ELASTICSEARCH_VERSION}
    depends_on:
      es:
        condition: service_healthy
    networks:
      - stack
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - ELASTICSEARCH_URL=http://es:9200
      - xpack.security.enabled=false
    ports:
      - 5601:5601
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/login"]
      retries: 6

  search-api:
    container_name: search-api
    build:
      context: ../../../../
      args:
        ARTIFACT: ./build/libs/search-api.jar
    networks:
      - stack
    image: search-api:itest-latest
    depends_on:
      es:
        condition: service_healthy
      kibana:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - ES_HOSTNAME=es
      - "JAVA_OPTS=-Xmx500m -Xms500m"
    ports:
      - 8482:8482

networks: {stack: {}}
